apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: prometheus
spec:
  interval: 2m
  chart:
    spec:
      chart: prometheus
      version: "20.0.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus