apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['188.40.172.121:9090']
      - job_name: "node-exporter"
        static_configs:
        - targets: ["localhost:9100"]
     - job_name: "cv"
       static_configs:
       - targets: ["188.40.172.121:80"]
