apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics
  namespace: metrics-server
spec:
  interval: 2m
  chart:
    spec:
      chart: metrics-server
      version: "0.6.3"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server