apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-dash
  namespace: grafana
spec:
  interval: 2m
  chart:
    spec:
      chart: grafana
      version: "6.52.9"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values:
    fullnameOverride: grafana-svc
    # Configure admin user and password
    adminUser: admin
    adminPassword: admin

    # Configure service type and port
    service:
      type: ClusterIP
      port: 80

    # Configure ingress settings
    ingressPathType: Prefix
    ingressPath: "/"
    ingress:
      ingressClassName: nginx
      hosts: 
        - grafana.mhasnain.dev
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: production-cluster-issuer
      host: grafana.mhasnain.dev

      spec:
        tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
        - hosts:
          - grafana.mhasnain.dev
          secretName: grafana-cert

    