apiVersion: apps/v1
kind: Deployment
metadata:
  name: masjid
  namespace: masjid
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: masjid
      app: hasnain-v2
  template:
    metadata:
      labels:
        tier: masjid
        app: hasnain-v2
    spec:
      containers:
      - name: masjid
        image: hasnainzaib/masjid:2.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: masjid
  namespace: masjid
spec:
  selector:
    tier: masjid
    app: hasnain-v2
  ports:
  - protocol: TCP
    name: masjid
    port: 80
    targetPort: 80
