apiVersion: apps/v1
kind: Deployment
metadata:
  name: masjid
  namespace: masjid
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: masjid
      app: hasnain
  template:
    metadata:
      labels:
        tier: masjid
        app: hasnain
    spec:
      containers:
      - name: masjid
        image: hasnainzaib/masjid:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: masjid
  namespace: masjid
spec:
  selector:
    tier: masjid
    app: hasnain
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
