apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 2m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  values:
    fullnameOverride: ingress-nginx
    publishService:
      enabled: false 
    metrics:
      enabled: true
      # port: 8443

    controller:
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"

